#!/bin/zsh

# --------- Seph's Zsh Prompt
# --------------------------------------------------------------
#            _                                          _   
#    _______| |__       _ __  _ __ ___  _ __ ___  _ __ | |_ 
#   |_  / __| '_ \     | '_ \| '__/ _ \| '_ ` _ \| '_ \| __|
#    / /\__ \ | | |    | |_) | | | (_) | | | | | | |_) | |_ 
#   /___|___/_| |_|____| .__/|_|  \___/|_| |_| |_| .__/ \__|
#                |_____|_|                       |_|        
#
# --------------------------------------------------------------

## --------- Zsh Prompt Function
zshPrompt () {
    zstyle ':vcs_info:git:*' formats '%F{121}%s%f %F{140}%b%f'
    newline=$'\n'
    zsh_prompt_border="$(tput setaf 62; repeatChar "-"; tput sgr0)"
    zsh_prompt_info=$(centerStringColor "%F{105}%n's%f %F{045}Z-Shell%f %F{139}v${ZSH_VERSION}%f %F{045}:%f %F{153}%N%f" "31")
    zsh_prompt_utility="${newline}%F{129}:%f %F{50}%m%f %f%F{212}{%f%F{087}%3~%f%F{212}}%f${newline}${newline}"
    zsh_prompt_cursor='${vcs_info_msg_0_} %F{069}⚘%f '

    PROMPT="${zsh_prompt_border}${zsh_prompt_info}${zsh_prompt_utility}${zsh_prompt_cursor}"
    RPROMPT="%F{223}%*%f %F{243}[%?]%f"
    PS2="⚘ "  
}
zshPrompt