#!/bin/sh

# --------- Seph's Shell Colors
# ------------------------------------------------------
#        _          _ _              _                
#    ___| |__   ___| | |    ___ ___ | | ___  _ __ ___ 
#   / __| '_ \ / _ \ | |   / __/ _ \| |/ _ \| '__/ __|
#   \__ \ | | |  __/ | |  | (_| (_) | | (_) | |  \__ \
#   |___/_| |_|\___|_|_|___\___\___/|_|\___/|_|  |___/
#                     |_____|                         
#
# ------------------------------------------------------

export norm=$(tput sgr0)
export purple54=$(tput setaf 54)
export purple111=$(tput setaf 111)
export purple105=$(tput setaf 105)
export blue75=$(tput setaf 75)
export blue=$(tput setaf 4)
export green85=$(tput setaf 85)
export normal=$(tput sgr0)
export reset=$(tput sgr0)
export purple60=$(tput setaf 60)
export purple62=$(tput setaf 62)
export purple63=$(tput setaf 63)
export purple99=$(tput setaf 99)
export purple75=$(tput setaf 75)
export purple129=$(tput setaf 129)
export purple153=$(tput setaf 153)
export blue45=$(tput setaf 45)
export blue81=$(tput setaf 81)
export blue87=$(tput setaf 87)
export blue153=$(tput setaf 153)
export green36=$(tput setaf 36)
export green50=$(tput setaf 50)
export pink132=$(tput setaf 132)
export pink163=$(tput setaf 163)
export pink139=$(tput setaf 139)
export pink201=$(tput setaf 201)
export pink212=$(tput setaf 212)
export yellow144=$(tput setaf 144)
export yellow192=$(tput setaf 192)