#!/bin/sh

######### • Shell Exports
##        _          _ _                              _       
##    ___| |__   ___| | |   _____  ___ __   ___  _ __| |_ ___ 
##   / __| '_ \ / _ \ | |  / _ \ \/ / '_ \ / _ \| '__| __/ __|
##   \__ \ | | |  __/ | | |  __/>  <| |_) | (_) | |  | |_\__ \
##   |___/_| |_|\___|_|_|  \___/_/\_\ .__/ \___/|_|   \__|___/
##                                  |_|                       
##
### ----------------------------------------------------------
##
######### XDG
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_CACHE_HOME="$HOME/.cache"
###
######### Shell History
case $0 in
    bash) 
        export HISTFILE="${XDG_STATE_HOME}"/bash/history 
        export BASH_SILENCE_DEPRECATION_WARNING=1
    ;;
    zsh) export HISTFILE="${XDG_STATE_HOME}"/zsh/history ;;
    *) : ;;
esac
###
######### LESS History
export LESSHISTFILE="${XDG_STATE_HOME:-$HOME/.config/less/history}"
###
######### Clean House
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
###
######### Programs
export EDITOR="vim"
export VISUAL="vim"
export TERMINAL="alacritty"
export BROWSER="brave"
export READER="zathura"
export FILE="lf"
###
######### Colors
export blue045="$(tput setaf 045)"
export purple062="$(tput setaf 062)"
export blue=$(tput setaf 4)
export normal=$(tput sgr0)
export reset=$(tput sgr0)
###
######### Misc
## Wget Config get from XDG_CONFIG_HOME or (:-) ~/.config....
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
###
######### Utility
export FONT_DIR_HOME="$HOME/Library/Fonts"
export current_shell="$0"
###
######### Rust
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
###
######### Zsh
## • Apple resets
## The following are used by Apple in /etc/zshrc, which
## is sourced _before_ `.zshrc`
## Wouldn't have to go in .zprofile otherwise.
## We could put them in .zshenv, but that file is best 
## kept as small as possible.
export SHELL_SESSION_DIR="$XDG_STATE_HOME/zsh/sessions"
export SHELL_SESSION_FILE="$SHELL_SESSION_DIR/$TERM_SESSION_ID"
###
### ----------------------------------------------------------