#!/bin/sh

# --------- Seph's Shell Profile
# ---------------------------------------------------------
#        _          _ _                    __ _ _      
#    ___| |__   ___| | |  _ __  _ __ ___  / _(_) | ___ 
#   / __| '_ \ / _ \ | | | '_ \| '__/ _ \| |_| | |/ _ \
#   \__ \ | | |  __/ | | | |_) | | | (_) |  _| | |  __/
#   |___/_| |_|\___|_|_| | .__/|_|  \___/|_| |_|_|\___|
#                        |_|                           
# ---------------------------------------------------------

# --------- Source Exports
if [ -f "${XDG_CONFIG_HOME}/shell/exports" ]; then
    . "${XDG_CONFIG_HOME}/shell/exports" &&
    export confirm_exports="exports"
fi

# --------- Check and add update $PATH
if [ -d "/usr/local/sbin" ] ; then export PATH="$PATH:/usr/local/sbin"; fi
if [ -d "$HOME/.local/bin" ] ; then export PATH="$PATH:$HOME/.local/bin"; fi
if [ -d "$HOME/dev/shell/bash/scripts" ] ; then export PATH="$PATH:$HOME/dev/shell/bash/scripts"; fi
if [ -d "/Applications" ] ; then export PATH="$PATH:/Applications"; fi

# --------- Cargo Rust
if [ -f "${XDG_DATA_HOME}/cargo/env" ]; then
    . "${XDG_DATA_HOME}/cargo/env"
    export confirm_cargo="cargo/env"
fi

# ENV=$HOME/.shinit; export ENV
# ---------------------------------------------------------